# Introduction

RNASequest, is a three-in-one RNAseq data analysis, data/app management, and publishing framework. It consists of a reproducible, configurable **Expression Analysis (EA)** module, multi-faceted result exploration in **Quickomics v2.0**, **Bookdown report** and **Online slide deck**, and a centralized data management system of apps and results generated by the workflow for future queries.

Expression Analysis (EA) is a Converter from a set of RNAseq analysis output to QuickOmics ([http://quickomics.bxgenomics.com](http://quickomics.bxgenomics.com){target="_blank"}) for interactive visualization.

The EA pipeline contains four main scripts:

  - **EAinit**
  
    This is the first step of the pipeline. It creates a directory storing files necessary for future steps.
    
    By default, the directory will be named based on the date of running the pipeline. For example, EA20220328_0 will be created since today is 2022-03-28. If the user runs EA again for the same dataset, the last digit will add up to avoid duplications: EA20220328_1
    
    
  - **EAqc**
  
    This is the second step of the pipeline. 
    
    It analyzes the covariates against the expression to determine if the expression is needed to be adjusted.
  
  
  - **EArun**
  
    After running EAqc, the following EArun step will perform differential expression analysis based on defined groups.
    
    It also produces QuickOmics objects for webserver loading.


  - **EAreport**
  
    The next step, EAreport, will generate a user-friendly bookdown report to visualize the EA pipeline results.

  - **EA2DA**
  
    The last step, EA2DA, produces 6 data files which are required for the [OmicsView](https://github.com/interactivereport/OmicsView){target="_blank"} project import.