# Online slide deck

Powered by reveal.js, the online slide deck is an R markdown template utilized by RNASequest to generate an interactive slide deck with emphasis on the graphical representation of QC and basic analysis plots, which makes the primary analysis presentation-ready for engaging biologists to discuss the initial results immediately. Again, it is also GitHub-friendly in terms of hosting.

Please visit an example of the online slide deck using the following link:

[https://interactivereport.github.io/RNASequest/ShinyOne/SRP199678/SlideDeck/index.html](https://interactivereport.github.io/RNASequest/ShinyOne/SRP199678/SlideDeck/index.html){target="_blank"}

Here is the tutorial to create your own slide deck after running the EA pipeline:

**1, Find the path of the bookdown.info.txt file, it is located in:**

```
***/YourPorjectName/EA******/BookdownReport/bookdown.info.txt
```

**2, Install the required package: [revealjs](https://cran.r-project.org/web/packages/revealjs/index.html){target="_blank"}**

```
conda activate ExpressionAnalysis

# Type 'R' to activate the R program in terminal
R
> install.packages(“revealjs”)

# After installation, quit the R session without saving the workspace
> quit()
Save workspace image? [y/n/c]: n
```

**3, Go to the RNASequest/src dir, and modify line #29 of script ‘Slidedeck.Rmd’:**

```
info_txt <- <your bookdown.info.txt path>
```

**4, Finally render the slide deck:**

The slide deck [Slidedeck.Rmd](https://github.com/interactivereport/RNASequest/blob/main/src/Slidedeck.Rmd){target="_blank"} script is under the /src directory of the RNASequest installation.

```
Rscript -e 'rmarkdown::render("~/RNASequest/src/Slidedeck.Rmd", output_file="yourslidedeck_name.html")'
```

Then it will generate **yourslidedeck_name.html** for visualization.

**Please note:**

1, Please run [EAreport](https://github.com/interactivereport/RNASequest/blob/main/EAreport){target="_blank"} first before generating the slide deck. For more details, please check the [manual](https://interactivereport.github.io/RNASequest/tutorial/docs/running-ea-pipeline.html#eareport){target="_blank"}.

2, The Slidedeck.Rmd only plots the first two covariates for ‘covariates plot’, so as to avoid plotting hundreds of figures/slides. If users want to plot a specific covariates, please edit the **‘config.yml’** file by moving your desired covariates to the first two.

For example:

```
# The original:
covariates_check: [cvt1, cvt2, …, cv_desire1, cv_desire2, …]

# Change it to:
covariates_check: [cv_desire1, cv_desire2, cvt1, cvt2, …]
```