#!/usr/bin/env bash

if [[ -n "$1" ]]; then
    source /etc/profile.d/modules_bash.sh
    module purge
    module load R/3.5.1
    
    Rscript $(dirname $0)/src/ToDiseaseAtlas.R $(dirname $0)/src/ $@
else
    echo "=============== EA2DA path/to/a/EAanalysis/config/file"
    echo "e.g.: EA2DA /camhpc/ngs/projects/TST11773/dnanexus/test_zhengyu.ouyang/QuickOmics_20210712180059/config.yml"
    echo "'EA2DA' can be used to create a folder containing the files for DiseaseAtlas project import"
    echo "==============="
    exit 0
fi
