#!/usr/bin/env bash

src="$(dirname $0)/src"
if [[ -n "$1" ]]; then
    if [[ ! -f "$src/.env" ]]; then
      echo "EAinit: Please run ./install to setup necessary env variables"
      exit
    fi
    
    source $src/.env;eval $condaEnv
    if [[ ! -f "$HOME/.gitconfig" ]] || [[ $(grep "$(dirname $0)/.git" ~/.gitconfig | wc -l) == 0 ]];then # 
      git config --global --add safe.directory $(dirname $0)/.git
    fi

    env -i src="$src" a=$1 b=$2 c=$3 bash -c 'source $src/.env;eval $condaEnv;Rscript $src/initConfig.R $src/ $a $b $c'
    
    #condaEnv=$(head -n 1 $(dirname $0)/src/sys.yml)
    #condaEnv=${condaEnv:1}
    #eval "$condaEnv"
    #Rscript $(dirname $0)/src/initConfig.R $(dirname $0)/src/ $@
else
    cd $(dirname $0)
    echo "##### ExpressionAnalysis: $(git config --get remote.origin.url)"
    echo "## Pipeline Path: $(dirname $0)"
    echo "## Pipeline Date: $(git show -s --format=%ci)"
    echo "## Head commit hash: $(git rev-parse HEAD)"
    echo "#####"
    echo
    
    echo "=============== EAinit path/to/a/DNAnexus/download/folder"
    echo "e.g.: EAinit /camhpc/ngs/projects/TST11000/dnanexus/20210709173527_fergal.casey"
    echo "A folder ('EA[date]') with files for EArun will be created in the input folder"
    #echo "Use 'EAinit path/to/a/DNAnexus/download/folder geneLength' to enable the gene length QC plots"
    echo ""
    echo "==============="
    exit 0
fi


