#!/usr/bin/env bash
# sva::ComBat_seq is not available in R/3.5.1

if [[ -n "$1" ]]; then
    source /etc/profile.d/modules_bash.sh
    module purge
    module load R/3.5.1
    
    Rscript $(dirname $0)/src/publish.R $(dirname $0)/src/ $@
else
    echo "=============== EApublish path/to/config/file"
    exePath=$(dirname $0)
    echo "'EApub' can be used to publish a RNAseq project to shinyone server!"
    echo "Please make sure the following two are satisfied before using EApub:"
    echo "\t1. The EArun was successfully called and checked on QuickOmic test website;"
    echo "\t2. Fill the buttom section "ShinyOne project manager" in config when possible."
    echo "==============="
    exit 0
fi
