#!/usr/bin/env bash
# sva::ComBat_seq is not available in R/3.5.1

if [[ -n "$1" ]]; then
    src="$(dirname $0)/src"
    if [[ ! -f "$src/.env" ]]; then
      echo "EApub: Please run ./install to setup necessary env variables"
      exit
    fi

    env -i src="$src" a=$1 b=$2 c=$3 bash -c 'set -o allexport;source $src/.env;set +o allexport;eval $condaEnv;Rscript $src/publish.R $src/ $a $b $c'

    #condaEnv=$(head -n 1 $(dirname $0)/src/sys.yml)
    #condaEnv=${condaEnv:1}
    #eval "$condaEnv"
    
    #Rscript $(dirname $0)/src/publish.R $(dirname $0)/src/ $@
else
    echo "=============== EApub path/to/config/file"
    exePath=$(dirname $0)
    echo "'EApub' can be used to publish a RNAseq project to shinyone server!"
    echo "Please make sure the following two are satisfied before using EApub:"
    echo "\t1. The EArun was successfully called and checked on QuickOmic test website;"
    echo "\t2. Fill the buttom section "ShinyOne project manager" in config when possible."
    echo "==============="
    exit 0
fi
