#!/usr/bin/env bash
# sva::ComBat_seq is not available in R/3.5.1

if [[ -n "$1" ]]; then
    condaEnv=$(head -n 1 $(dirname $0)/src/sys.yml)
    condaEnv=${condaEnv:1}
    eval "$condaEnv"
    
    Rscript $(dirname $0)/src/QCanalysis.R $(dirname $0)/src/ $@
else
    echo "=============== EAqc path/to/config/file"
    exePath=$(dirname $0)
    echo "An example config file can be found: $exePath/example/config.yml"
    echo "'EAinit' can be used to create a config file for a RNAseq project downloaded from DNAnexus"
    echo "==============="
    exit 0
fi
