#!/usr/bin/env bash
# sva::ComBat_seq is not available in R/3.5.1

if [[ -n "$1" ]]; then
    src="$(dirname $0)/src"
    if [[ ! -f "$src/.env" ]]; then
      echo "EAqc: Please run ./install to setup necessary env variables"
      exit
    fi
    source $src/.env;eval $condaEnv
    if [[ ! -f "$HOME/.gitconfig" ]] || [[ $(grep "$(dirname $0)/.git" ~/.gitconfig | wc -l) == 0 ]];then # 
      git config --global --add safe.directory $(dirname $0)/.git
    fi

    env -i src="$src" a=$1 b=$2 c=$3 bash -c 'source $src/.env;eval $condaEnv;Rscript $src/QCanalysis.R $src/ $a $b $c'
    #condaEnv=$(head -n 1 $(dirname $0)/src/sys.yml)
    #condaEnv=${condaEnv:1}
    #eval "$condaEnv"
    
    #Rscript $(dirname $0)/src/QCanalysis.R $(dirname $0)/src/ $@
else
    echo "=============== EAqc path/to/config/file"
    exePath=$(dirname $0)
    echo "An example config file can be found: $exePath/example/config.yml"
    echo "'EAinit' can be used to create a config file for a RNAseq project downloaded from DNAnexus"
    echo "==============="
    exit 0
fi
