#!/usr/bin/env bash
# sva::ComBat_seq is not available in R/3.5.1

if [[ -n "$1" ]]; then
    source /etc/profile.d/modules_bash.sh
    module purge
    module load R/3.5.1
    
    Rscript $(dirname $0)/src/DEanalysis.R $(dirname $0)/src/ $@
else
    echo "=============== EArun path/to/config/file"
    echo "This function is used to process the bulk RNAseq data and produce the QuickOmics R object."
    exePath=$(dirname $0)
    echo "An example config file can be found: $exePath/example/config.yml"
    echo "'EAinit' can be used to create a config file for a RNAseq project downloaded from DNAnexus"
    echo "==============="
    exit 0
fi
