#!/usr/bin/env bash
# sva::ComBat_seq is not available in R/3.5.1

if [[ -n "$1" ]]; then
    source /etc/profile.d/modules_bash.sh
    module purge
    module load R/3.5.1
    
    Rscript $(dirname $0)/src/prjSplit.R $(dirname $0)/src/ $@
else
    echo "=============== EAsplit path/to/config/file"
    exePath=$(dirname $0)
    echo "An example config file can be found: $exePath/example/config.yml"
    echo "'EAsplit' can be used to split a project into sub projects based on one meta column definition (split_meta in config)."
    echo "==============="
    exit 0
fi
