#!/usr/bin/env bash

condaPath=$(which conda)
if [[ ${#condaPath} -lt 3 ]]; then
    echo "Missing conda"
    echo "Please install conda and add it into PATH"
    exit
else
    echo "conda in $condaPath"
fi

conda env create -f install.yml
condaPath=$(dirname $(dirname $condaPath))
sed -i "1s|^|#. $condaPath/etc/profile.d/conda.sh;conda activate ExpressionAnalysis\n|" src/sys.yml

conda activate ExpressionAnalysis
R -q -e 'if(!require(revealjs)) install.packages("revealjs",repos = "http://cran.us.r-project.org")'

#printf 'Please install R revealjs package in the ExpressionAnalysis conda environment.\nR\ninstall.packages("revealjs")\n'
