#!/usr/bin/env bash

condaPath=$(which conda)
if [[ ${#condaPath} -lt 3 ]]; then
    echo "Missing conda"
    echo "Please install conda and add it into PATH"
    exit
else
    echo "conda in $condaPath"
fi

src="$(dirname $0)/src"
conda env create -f install.yml
condaPath=$(dirname $(dirname $condaPath))
# sed -i "1s|^|#. $condaPath/etc/profile.d/conda.sh;conda activate ExpressionAnalysis\n|" src/sys.yml
echo "export condaEnv='. $condaPath/etc/profile.d/conda.sh;conda activate ExpressionAnalysis'" > $src/.env
echo "export PATH=$PATH" >> $src/.env
echo "export OPENBLAS_NUM_THREADS=1" >> $src/.env
echo "export SGE_EXECD_PORT=$SGE_EXECD_PORT" >> $src/.env
echo "export SGE_QMASTER_PORT=$SGE_QMASTER_PORT" >> $src/.env
echo "export SGE_ROOT=$SGE_ROOT" >> $src/.env

## additional packages which are not available on anaconda
env -i src="$src" bash -c 'set -o allexport;source $src/.env;set +o allexport;eval $condaEnv;R -q -e '"'"'suppressWarnings({if(!require(revealjs)) install.packages("revealjs",repos = "https://cran.us.r-project.org")})'"'"

#conda activate ExpressionAnalysis
#R -q -e 'if(!require(revealjs)) install.packages("revealjs",repos = "http://cran.us.r-project.org")'

#printf 'Please install R revealjs package in the ExpressionAnalysis conda environment.\nR\ninstall.packages("revealjs")\n'
