```{r, echo=FALSE}

#Retrieve information from the previously saved bookdown.info.txt file
PWD <- system("pwd", intern = TRUE)
Info <- paste0(PWD, "/bookdown.info.txt")
Data <- read.table(Info)
Source_code <- Data$V2[1]
Working_dir <- Data$V2[2]
Config_file <- Data$V2[3]

#Extract information from the Config_file
config <- sapply(yaml::read_yaml(Config_file),unlist)
sysConfig <- yaml::read_yaml(paste0(Source_code,"sys.yml"))
ProjectName <- config$prj_name
```

--- 
title: Bookdown report of `r ProjectName`
date: "Generated on `r Sys.Date()`"
site: bookdown::bookdown_site
---

This is a summary report generated by EAreport (part of ExpressionAnalysis) using Bookdown.

# Introduction {-}

This report contains basic plots and tables which provide an overview of the current project: **`r config$prj_name`**.

The ExpressionAnalysis (EA) pipeline analyzes RNAseq data provided by the user, or from GEO database, and generates results for interactive visualization. This report is part of ExpressionAnalysis (EA) output, and contains key results of the project.

For more flexible and interactive visualization, please upload the following Rdata files to [Quickomics](http://quickomics.bxgenomics.com/).

**`r ProjectName`_estCount.rds**

**`r ProjectName`_network.RData**

**`r ProjectName`.RData**

**`r ProjectName`.csv**

The following sections are included in this bookdown report:

1, QC

2, Covariates plots

3, PCA plots

4, Volcano plots

5, Heatmap plots
