# ====== The project information ==========
# prj_name: will be used as a part of the output file names, and 
#           project information in QuickOmics, which can be changed in output CSV file
# prj_counts: 
# prj_effLength: 
# prj_seqQC: 
# prj_TPM: 
# DA_file_outpath: folder to store the data files used for DiseaseAtlas project import. 
# sample_meta: sample definition file, meta data, rows as samples, columns as phenotypes
# sample_name: the column name in the above table which contains the sample name used for the count matrix
#               empty means the first column (the row names)
# sample_alias: the column name in the meta table to replace the sample names, empty means no-replace
# split_meta: the column name in the meta table is used to split the data into sub folder
# min_count: 
# min_sample:
#               The genes considered in the analysis require at least (min_sample) samples expressed
#               at least (min_count).
# count_prior: the small numeric added before log transform
# output: the result folder
prj_name: initPrjName
prj_title: initPrjTitle
prj_counts: initCounts
prj_effLength: initEffLength
prj_seqQC: initSeqQC
prj_TPM: initTPM
sample_meta: initPrjMeta
sample_factor: initPrjFactor
sample_name: Sample_Name
sample_alias:
split_meta:
species: initSpecies
gene_annotation: initGeneAnnotation
min_count: 1
min_sample: 1
count_prior: 0.25
output: initOutput
DA_file_outpath: initOutput/DA_Import_Files
core: 2
parallel: false # or sge or slurm
qsubTime: 180 #in minites, 3hr # not used for slurm
min_median_effective_length: 5 #nominal length will be used If the median effective length is smaller than the specified
seqQC_replot: false
geneLength_QC: false
rmGeneStartWith: [] # remove genes whose names start with specified

# ====== The QC parameters ========
# covariates_check: The listed covariates will checked against PCA of 
#                   log TPM before and after covariates removal
# covariates_rm: the global covariates to be removed from expression visualization 
covariates_check: initCovariates
covariates_check_PCcutoff: 5
covariates_check_FDRcutoff: 0.1
covariates_check_plotNcol: 3
covariates_adjust: []
covariates_method: limma # 'limma': (default) adjusts multiple covariates at the same time, 'combat': adjusts only one covariate

# ====== The comparison information for quickOmics convert ========
# comparison_file: comparison file defnition file
# sample_group: the column name(s) in the meta table which will be used to calculate the
#               mean/sd for all group combinations shown in QuickOmics.
#               If empty, the first group variable in the comparison file will be used
comparison_file: initPrjComp
sample_group: []

# ====== The gene network parameters ===============
# gene_network_high_variable_N: the number of highly variable genes (sorted by sd) used for
#                               the gene network construction
# gene_network_cor_cutoff: the Pearson's correlation coefficients cutoff for the network edge
# gene_network_p_cutoff: the correlation p-value cutoff for the network edge
# gene_network_max_edge: The maximum network edge (will increase the cutoff if needed)
gene_network_high_variable_N: 10000
gene_network_cor_cutoff: 0.7
gene_network_p_cutoff: 0.05
gene_network_max_edge: 2e6
gene_network_min_edge: 2e3

# ====== This section for ShinyOne project manager =========
shinyOne_Title: 
shinyOne_Description: 
shinyOne_Data_Generated_By: 
shinyOne_Disease_Model:  #e.g. AD, ALS
shinyOne_Biological_System:  #e.g. Brain, Heart
shinyOne_Sample_Type:   #e.g. Blood, Cell
shinyOne_Technology_Platform: RNA-Seq
shinyOne_Data_Source: Internal
shinyOne_Data_Cleaning:


